config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get "/about" => "welcome#about"


  post "salons/search" => "salons#search"
  get "salons/search" => "salons#search"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  get "/profile" => "users#profile", as: "profile"

  resources :users

  get "/profile/edit" => "users#edit", as: "edit_profile"


  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/auth/facebook" => "sessions#create_from_omniauth"
  get "/auth/facebook/callback" => "sessions#create_from_omniauth"


  resources :salons
end

app/models/user.rb
class User < ApplicationRecord

has_secure_password  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  has_many :authentications, dependent: :destroy
  has_many :salons

  enum role: [:client, :owner, :super_admin]


  def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     first_name: auth_hash["info"]["first_name"],
     last_name: auth_hash["info"]["last_name"],
     avatar: auth_hash["info"]["image"],
     email: auth_hash["info"]["email"],
     password_digest: SecureRandom.hex(10)
   )
   user.authentications << authentication
   return user
  end

 # grab tokens to access different providers' user info
  def google_token
    x = self.authentications.find_by(provider: 'google')
    return x.token unless x.nil?
  end

  def fb_token
    x = self.authentications.find_by(provider: 'facebook')
    return x.token unless x.nil?
  end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
  
  def new
    @user = User.new
  end

  def create
    p params
    @user = User.new(user_params)
    if @user.save!
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully created an account"
      redirect_to root_url
    else
    redirect_to '/signup'      
    end
  end

def show
  @user = User.find(params[:id])
  @salon = @user.salons
end

  def profile
    @salons = current_user.salons
    @salon = Salon.new
  end

  def edit
    render template: "users/edit"
  end

  def update
    current_user.update(user_params)
      redirect_to '/profile'
  end

  def destroy
    @user.destroy
    redirect_to '/'
  end

  

private

def user_params
params.require(:user).permit(:id, :first_name, :last_name, :email, :password, :role, :avatar)
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_display.html.erb
<!-- <div class="wrapper">
  <div class= "container margin-bot">
    <div class="row">
      <div class="col-6">
        <div class="card w-100 mt-5" style = " padding: 2%">
          <div>
            <h1><strong><%= @user.first_name %></strong></h1>
            <p><strong>Location: </strong><%= @user.location %></p>
            <p><strong>Country: </strong><%= @user.country %></p>
            <p><strong>Owner: </strong><%= @user.user.first_name%> <%= @user.user.last_name%></p>
            <p><strong>Contact: </strong><%= @user.contact %></p>
            <span>
            <%# if can? :update, @salon %>
            <%#= button_to "Edit", edit_salon_path(@salon), :method => "get", class:"btn btn-primary" %>
            <% #end %>

            <%# if can? :destroy, @salon %>
            <%#= button_to "Delete", @salon, :method => "delete", class:"btn btn-primary" %>
            <% #end %>
            </span>           
          </div>
        </div>
      </div>
      <div class="col-6">
          <div class="card w-100 mt-5" style = " padding: 2%">
      <div id="map" class="wrapper-xs"></div>
      </div>
    </div>
    </div>    
  </div>
</div> -->

app/views/users/_form.html.erb
         <%= f.label :role, 'I own a hair busines', :value => 'owner' %>
         <%= f.radio_button :role, 'owner' %> 
       

app/views/users/edit.html.erb
Edit page

<%= form_for current_user do |f| %>
<%= f.label :role, 'I own a hair busines', :value => 'owner' %>
<%= f.radio_button :role, 'owner' %> 
<div class= "submit"><%= f.submit class: "btn btn-large btn-dark" %></div>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col"></div>
      <div class="col">
        <h1>Signup</h1>        
        <%#= form_for :user, url: '/users' do |f| %>
        <%#= f.label :first_name %>  
        <!-- <br>
        <%#= f.text_field :first_name %>
        <br>
        <%#= f.label :last_name %> 
        <br>
        <%#= f.text_field :last_name %>
        <br>
        <%#= f.label :email %> 
        <br>
        <%#= f.text_field :email %>
        <br>
        <%#= f.label :password %>  
        <br>  
        <%#= f.password_field :password %>
        <br>
        <br>   -->
         <%= f.label :role, 'I own a hair busines', :value => 'owner' %>
         <%= f.radio_button :role, 'owner' %> 
        <br>
        <br>
        <%= f.submit "Save!",  class: 'btn btn-primary' %>
        <% end %>
      </div>
    <div class="col"></div>
  </div>
</div>

app/views/users/profile.html.erb
  <!-- CLIENT PROFILE -->
<% if current_user.role == "client" %>

  <div class="container-fluid" id="profile">
    <div class="salon-header"> <h2 id="salon-form-head">Edit Details</h2> </div>
    <p id = "image"><%= image_tag current_user.avatar, :class => 'avatar'%></p>
    <h1 class = "profile"><strong><%= current_user.first_name %> <%= current_user.last_name %></strong></h1>
    <p class = "mx-auto mt-0">Joined: <%= current_user.created_at.strftime("%B") %> <%= current_user.created_at.strftime("%Y") %> </p>
          <p>
            <%= form_for current_user do |f| %>
            <h5>I own a salon / want to list my hair services:</h5>   
            <%= f.label :role, 'Yes', :value => 'owner' %>
            <%= f.radio_button :role, 'owner' %> 
            <%= f.label :role, 'No', :value => 'client' %>
            <%= f.radio_button :role, 'client' %> 
          </p>
          <p>
            <%= f.submit "Update Profile", class: "btn btn-large btn-dark" %>
          </p>
          <p class= 'show-button'><%= link_to "<button>All Salons</button>".html_safe, salons_path, :method => "get", class: "btn" %>
            </p>
          </p>
      <% end %>
  </div> 

<% else %>

<!-- OWNER PROFILE -->
  <div class="container-fluid" id="profile">
    <div class="profile-header"><h2 id="profile-form-head">My Profile</h2></div>
      <p id = "image">
      <% if current_user.avatar.present? %>
        <%= image_tag current_user.avatar, :class => 'avatar'%>
      <% else %>
      <% end %>
      </p>
      <h1 class = "profile"><strong><%= current_user.first_name %> <%= current_user.last_name %></strong></h1>
      <p class = "mx-auto mt-0">Joined: <%= current_user.created_at.strftime("%B") %> <%= current_user.created_at.strftime("%Y") %> </p>
    <div class="profile-header"><h2 id="profile-form-head">My Salon(s)</h2></div>
      <div id="listed"><h5 class ='listed'> You have listed the following salons: </h5>
        <ul> <% @salons.each do |salon| %>
          <li id='salon-list'> 
            <div class='row'>
              <div class='col' id='sal-name'> <%= salon.business_name %></div> 
              <div class='col'><%= button_to "View", salon_path(salon), method: :get, :id => "view" %><br>
            </div>
          </li>
          <% end %>
        </ul>
      <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newSalonList">
          List New Salon
        </button>
        <p class= 'show-button mt-0'><%= button_to "All Salons", '/salons', :method => "get", class: "btn" %></p>
        <!-- Modal -->
        <div class="modal fade-lg" id="newSalonList" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-lg" role="document" id="new-modal">
            <div class="modal-content">
              <div class="modal-body">
                <div class="salon-header">
                  <h2 id="salon-form-head">
                    List New Salon
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </h2>
                </div>
                 <%= form_for @salon do |f| %>
                   <%= render partial: '/salons/form', :locals => {:f => f } %>  
                   <div class= "submit mt-2"><%= f.submit "List Salon", class: "btn" %></div>
                 <% end %>
                 <br>
                 <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>