config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get "/about" => "welcome#about"


  post "salons/search" => "salons#search"
  get "salons/search" => "salons#search"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  get "/profile" => "users#profile", as: "profile"

  resources :users

  get "/profile/edit" => "users#edit", as: "edit_profile"


  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/auth/facebook" => "sessions#create_from_omniauth"
  get "/auth/facebook/callback" => "sessions#create_from_omniauth"


  resources :salons
end

app/models/salon.rb
class Salon < ApplicationRecord
  belongs_to :user

  scope :country, -> (country) { where("country ILIKE ?", "%#{country}%") } 
  scope :location, -> (location) { where("location ILIKE ?", "%#{location}%") } 
  scope :suburb, -> (suburb) { where("suburb ILIKE ?", "%#{suburb}%") } 

  paginates_per 8

end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
	  before_action :set_salon, only: [:show, :edit, :update, :destroy]
  
  def index
    @salons = Salon.all.order("created_at DESC").page(params[:page])
  end

  def new
    @salon = Salon.new
  end 

  def create
    @salon = Salon.new(salon_params)
    @salon.user_id = current_user.id
      if @salon.save
        flash[:success] = 'You have successfully listed your services!'
        redirect_to @salon
      else
        flash[:danger] = 'Something went wrong with salon your services!'
        redirect_to new_salon_path(@salon)
      end
  end   

  def show
  end

  def edit
    current_user = @salon.user_id
  end

  def update
    if @salon.update(salon_params)
      redirect_to @salon
    else
      redirect_to edit_salon_path
    end
  end

  def destroy
    @salon.destroy
    redirect_to "/profile"
  end

  def search
    @salons =  Salon.all
      filtering_params(params).each do |key,value|
        @salons = @salons.public_send(key, value) if value.present?
        if @salons.empty?
          flash.now[:notice] = "Sorry there are no results for your search. Try again."
        end
        @salons = @salons.page(params[:page]).order(created_at: :desc)
        respond_to do |format|
          format.js
          format.html {render "index"}
        end
      end
  end

  def insta
    @insta = @salon.instafeed
    @insta = @insta.gsub(/^(.{39,}?).*$/m,'\1/embed')
  end
    helper_method :insta

private

  def salon_params
    params.require(:salon).permit(:id, :page, :country, :location, :title, :description, :business_name, :contact,:contact_person, :suburb, :address, :facebook, :instagram, :website, :instafeed, speciality:[])
  end

  def set_salon
      @salon = Salon.find(params[:id]) 
  end

  def filtering_params(params)
    params.slice(:country, :location, :suburb, :instafeed)
  end


end

app/helpers/salons_helper.rb
module SalonsHelper
end

app/views/salons/_display.html.erb
<div class="row" id="sal-row">
    <% @salons.each do |salon| %>
      <div class="col-lg-3">  
        <div class="d-flex align-items-center align-content-stretch flex-wrap">
          <div class="card mt-2 text-center">
            <div class="card-header"><h2><%= link_to salon.business_name ,salon_path(salon), class:"salon-link" %></h2></div>
               <div class="card-body">
                <!-- <p class="card-text"><#%= label_tag :country, 'Created on:' %> <%= salon.created_at %></p> -->
                <p class="card-text"><%= label_tag :country, 'Country:' %> <%= salon.country %></p>
                <p class="card-text"><%= label_tag :location, 'City:' %> <%= salon.location %></p>
                <p class="card-text"><%= label_tag :area, 'Area:' %> <%= salon.suburb %> </p>
                <p class="card-text"><%= label_tag :speciality, 'Speciality:' %><br><%= salon.speciality * " / " %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

app/views/salons/_form.html.erb
<div class="form-group">
    <%= label_tag :business_name, 'Salon' %>
     <%= f.text_field :business_name, class: 'form-control', placeholder: 'Salon' %>
  </div>
    <div class="form-row">
    <div class="form-group col-md-6">
      <%= label_tag :contact, 'Contact Number' %>
      <%= f.text_field  :contact, class: 'form-control', placeholder: 'Contact Number' %>
    </div>
    <div class="form-group col-md-6">
      <%= label_tag :contact_person, 'Contact Person' %>
      <%= f.text_field  :contact_person, class: 'form-control', placeholder: 'Contact Person' %>
    </div>
  </div>
 <!-- Address -->
  <div class="form-row">
    <div class="form-group col-md-4">
      <%= label_tag :country, 'Country' %>
      <%= f.text_field  :country, class: 'form-control', placeholder: 'Country' %>
    </div>
    <div class="form-group col-md-4">
      <%= label_tag :location, 'City / Town' %>
      <%= f.text_field  :location, class: 'form-control', placeholder: 'City / Town' %>
    </div>
    <div class="form-group col-md-4">
      <%= label_tag :area, 'Area' %>
      <%= f.text_field  :suburb, class: 'form-control', placeholder: 'Area' %>
    </div>
  </div>
   <div class="form-group">
     <%= label_tag :address, 'Address' %>
      <%= f.text_field  :address, class: 'form-control', placeholder: 'Address' %>
  </div>
  <!-- Social Media -->
  <div class="form-row">
    <div class="form-group col-md-4">
    <%= label_tag :website, 'Website*' %>
    <%= f.text_field  :website, class: 'form-control', placeholder: 'https://www.salonwebsite.com' %>
  </div>
    <div class="form-group col-md-4">
    <%= label_tag :facebook, 'Facebook*' %>
    <%= f.text_field  :facebook, class: 'form-control', placeholder: 'https://www.facebookpage.com' %>
  </div>
  <div class="form-group col-md-4">
    <%= label_tag :instagram, 'Instagram*' %>
    <%= f.text_field  :instagram, class: 'form-control', placeholder: 'https://www.instagrampage.com' %>
  </div>
</div>
<!-- Speciality -->
 <div class="form-row" id="speciality">
  <div class="form-group col-md-2">
      <%= label_tag :speciality, 'Speciality' %>
    </div>
    <div class="form-group col-md-2">
      <%= f.check_box :speciality, {multiple: true}, "Natural Hair", nil %>
      <h8>Natural Hair</h8>
    </div>
    <div class="form-group col-md-2">
      <%= f.check_box :speciality, {multiple: true}, "Relaxed Hair", nil %>
      Relaxed Hair
    </div>
    <div class="form-group col-md-2">
      <%= f.check_box :speciality, {multiple: true}, "Braids", nil %>
      Braids
    </div>
    <div class="form-group col-md-2">
      <%= f.check_box :speciality, {multiple: true}, "Weaves", nil %>
      Weaves
    </div>
    <div class="form-group col-md-2">
      <%= f.check_box :speciality, {multiple: true}, "Dreadlocs", nil %>
      'Locs
    </div>
  </div>
    <div class="form-group">
      <%= label_tag :description, 'Additional Details' %>
      <%= f.text_field :description, class: 'form-control', id: 'description', placeholder: 'Describe what your salon offers in detail...' %>
    </div>

app/views/salons/index.html.erb
<!-- INDEX PAGE -->
<div class="container-fluid align-items-center mx-auto" id="index">
  <div class="container-fluid mb-1" id="search_row">
    <div class="search mt-4">
      <%= form_tag salons_search_path, id: "search-front", method: :get, remote: true do %>
       <%= text_field_tag :country, params[:country], placeholder: ' Country', class:"search_field" %> 
       <%= text_field_tag :location, params[:location], placeholder: ' City', class:"search_field" %> 
       <%= submit_tag "Search", name: nil, class:"btn" %>
      <% end %>
    </div>
  </div>
  <!-- SEARCH RESULTS -->
  <div class="container-fluid mt-1" id ="search_list" >
    <%= render partial: '/salons/display', object: @salons %>
  </div>
    <div class= "page mt-4"><%= paginate @salons %></div>
</div>

app/views/salons/search.js.erb
$("#search_list").html("");
$("<%= j render(partial:'display', object: @salons)%>").appendTo("#search_list");
$("#alert").html("<%= flash[:notice] %>");

app/views/salons/show.html.erb
<!-- SHOW PAGE -->
<div class="container-fluid" id="show-page">
  <div class="row">
    <div class="col-lg-6">
      <div class="salon-header">
			 <h2 id="salon-form-head"><%= @salon.business_name %></h2>
	    </div>   
    	<div class="info">
        <p>
          <%= link_to(image_tag("website.png"), "#{@salon.website}", { target: '_blank' }) if @salon.website.present? %>
          <%= link_to(image_tag("facebook.png"), "#{@salon.facebook}", { target: '_blank' }) if @salon.facebook.present?  %>
          <%= link_to(image_tag("instagram.png"), "#{@salon.instagram}", { target: '_blank' }) if @salon.instagram.present?  %>
        </p>            
    		<p><%= label_tag :contact, 'Contact Number:' %> <%= @salon.contact %></p>
        <p><%= label_tag :contact_person, 'Contact Person:' %> <%= @salon.contact_person %></p>
        <p><%= label_tag :country, 'Country:' %> <%= @salon.country %></p>
        <p><%= label_tag :location, 'City / Town:' %> <%= @salon.location %> </p>
        <p><%= label_tag :area, 'Area:' %> <%= @salon.suburb %> </p>
        <p><%= label_tag :address, 'Address:' %> <%= @salon.address %> </p>
        <p><%= label_tag :speciality, 'Speciality:' %> <%= @salon.speciality * "," %></p>
        <p><h7 class="listed"><%= @salon.description %></h7></p>
        <!-- Button Trigger Modal -->
        <p class= 'show-button'>
          <% if can? :update, @salon %>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editSalon">
            Edit</button>
          <% end %>
        </p>
        <p class= 'show-button'>
          <% if can? :destroy, @salon %>
            <%= button_to "Delete", @salon, :method => "delete", data: {confirm: "Are you sure you want to delete this listing?"}, class: "btn" %>
          <% end %>
        </p>
        <p class= 'show-button'><%= button_to "All Salons", '/salons', :method => "get", class: "btn" %></p>
        <p class= 'show-button' ><%= link_to 'Back', :back , :style=>'color: #0E2A36;' %></p>
      </div>
         <!--  Edit Modal -->
      <div class="modal fade-lg" id="editSalon" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document" id="new-modal">
          <div class="modal-content">
            <div class="modal-body">
              <div class="salon-header">
                <h2 id="salon-form-head">
                  Edit Salon
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </h2>
              </div>
               <%= form_for @salon do |f| %>
                <%= render partial: '/salons/form', :locals => {:f => f } %>  
                  <div class= "submit mt-2"><%= f.submit "Update", class: "btn" %></div>
               <% end %>
               <br>
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- INSTAGRAM -->

    <div class="col-lg-6">
      <div class="salon-header">
        <h2 id="salon-form-head">
          Showcase Gallery
        </h2>
      </div> 
      <!-- Button trigger modal -->
      <div>
        <% if can? :update, @salon %>
          <p id='instabutton'><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#instafeed" title="Show case your work by sharing a multiphoto Instagram post")>Instagram + </button></p>
        <% end %>
      </div>
      <!-- iFRAME -->
      <div class='iframe-holder'>
      <% if @salon.instafeed.present? %>
        <iframe width="300px" height="300px" style="height:100%;width:55%;" src="<%= insta %>" frameborder="0"></iframe>
      <% else %>
        <div class="container-fluid mt-5 pt-5" width="300px;" height="300px;">
          <%= image_tag("instalogo.png") %> 
          <h5 class="listed">No Shared Instagram Post yet...</h5>
        </div>
      <% end %>
      </div>

    <!-- Instagram Modal -->
    <div class="modal fade" id="instafeed" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Share showcase Instagram Post to Salon Profile</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= form_for @salon do |f| %>
              <div class="form-group">
                <%= label_tag :instafeed, 'Add Instagram Post' %>
                <%= f.text_field  :instafeed, class: 'form-control', placeholder: 'Copy and paste a multi photo Instagram link' %>
                </div>
                <div class= "submit mt-2"><%= f.submit "Save", class: "btn" %></div>
             <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
    </div>
  </div>
</div>